name: Deploy RAG Frontend 

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete existing 'index.html'
      run: |
        az storage blob delete \
            --account-name ${{ secrets.BLOB_ACCOUNT_URL }} \
            --container-name '$web' \
            --name 'index.html' \
            --account-key ${{ secrets.BLOB_ACCOUNT_KEY }}
    - name: Upload modified 'index.html'
      run: |
        az storage blob upload \
            --account-name ${{ secrets.BLOB_ACCOUNT_URL }} \
            --container-name '$web' \
            --name 'index.html' \
            --file index.html \
            --account-key ${{ secrets.BLOB_ACCOUNT_KEY }}

            